stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/data.csv

    outs:
    - data/raw/data.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/data.csv
    outs:
    - data/processed/train_data.csv
    - data/processed/test_data.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_data.csv
    - data/processed/test_data.csv
    - src/train_and_evaluate.py
    metrics:
    - report/scores.json:
        cache: false