base:
  project: SAHeart-project
  random_state: 999
  target_col: chd

data_source:
  s3_source: data_given/data.csv
  

load_data:
  raw_dataset_csv: data/raw/data.csv

split_data:
  train_path: data/processed/train_data.csv
  test_path: data/processed/test_data.csv
  test_size: 0.3

rf_params:
  n_estimators: 200
  max_depth: 30
  oob_score: True

model_dir: saved_models

reports:
  scores: report/scores.json
  roc: report/roc.json
  prc: report/prc.json
  auc: report/auc.json
